// [config]
// expect_result: pass
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// From the ARB_compute_shader spec:
//
//     Layout qualifier identifiers for compute shader inputs are the work-group
//     size qualifiers:
//
//         layout-qualifier-id
//             local_size_x = integer-constant
//             local_size_y = integer-constant
//             local_size_z = integer-constant
//
//     <local_size_x>, <local_size_y>, and <local_size_z> are used to define the
//     local size of the kernel defined by the compute shader in the first,
//     second, and third dimension, respectively. The default size in each
//     dimension is 1. If a shader does not specify a size for one of the
//     dimensions, that dimension will have a size of 1.
//
// This test verifies that unspecified local_size dimensions default
// to 1, by taking advantage of the fact that conflicting layouts will
// cause a compiler error.


#version 330
#extension GL_ARB_compute_shader: enable

// All 3 of the following layouts should be equivalent, since
// unspecified sizes default to 1.
layout(local_size_x = 1) in;
layout(local_size_y = 1) in;
layout(local_size_z = 1) in;

void main()
{
}
