// [config]
// expect_result: fail
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// From the GLSL 4.4 spec, section 7.1 (Built-in Language Variables):
//
//     It is a compile-time error to use gl_WorkGroupSize in a shader
//     that does not declare a fixed local group size ...

#version 330
#extension GL_ARB_compute_shader: enable

void main()
{
  uvec3 size = gl_WorkGroupSize;
}
