// [config]
// expect_result: fail
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// From the ARB_compute_shader spec:
//
//     [If an input layout qualifier] is declared more than once in
//     the same shader, all those declarations must indicate the same
//     local work-group size; otherwise a compile-time error results.

#version 330
#extension GL_ARB_compute_shader: enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(local_size_x = 1, local_size_y = 1, local_size_z = 2) in;

void main()
{
}
