// [config]
// expect_result: fail
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// From the ARB_compute_shader spec:
//
//     <local_size_x>, <local_size_y>, and <local_size_z> are used to
//     define the local size of the kernel defined by the compute
//     shader in the first, second, and third dimension,
//     respectively. The default size in each dimension is 1. If a
//     shader does not specify a size for one of the dimensions, that
//     dimension will have a size of 1.
//
// Although it's not explicitly stated, it seems reasonable to assume
// that a local size less than 0 is prohibited.

#version 330
#extension GL_ARB_compute_shader: enable

layout(local_size_y = -1) in;

void main()
{
}
