// [config]
// expect_result: fail
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// From the ARB_compute_shader spec:
//
//     Compute shaders do not permit user-defined input variables and
//     do not form a formal interface with any other shader stage.

#version 330
#extension GL_ARB_compute_shader: enable

layout(local_size_x = 1) in;

in int i;

void main()
{
}
